name: jaspr_router
description: A routing component for jaspr.
version: 0.1.0
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  jaspr: ^0.1.0

dev_dependencies:
  jaspr_test: ^0.1.0
  lints: ^1.0.0
  test: ^1.16.0