name: sorare_agent_landing_page
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.12.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.10
  jaspr_builder: ^0.12.0
  lints: ^3.0.0

jaspr:
  mode: client

