name: sorare_agent_landing_page
description: A landing page built with Jaspr for Sorare Agent
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.1.0
  jaspr_router: ^0.1.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  jaspr_builder: ^0.1.0
  lints: ^1.0.0
  webdev: 2.7.7