name: jaspr_basic_template
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.4
  jaspr: ^0.2.0
  jaspr_riverpod: ^0.1.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0

dependency_overrides:
  jaspr:
    path: ../../../jaspr
  jaspr_riverpod:
    path: ../../../jaspr_riverpod