include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - templates/jaspr_export

linter:
  rules:
    sort_pub_dependencies: true
    prefer_relative_imports: true
    directives_ordering: true