name: jaspr_pad
description: Dartpad inspired online-editor for jaspr built with jaspr.
version: 0.1.0
publish_to: none
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analysis_server_lib: ^0.2.2
  archive: ^3.3.0
  codemirror: ^0.7.3+5.65.2
  dart_mappable: ^1.1.0
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  jaspr: ^0.2.0
  jaspr_riverpod: ^0.1.0
  markdown: ^5.0.0
  shelf_router: ^1.1.2
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.7
  build_web_compilers: ^3.2.2
  dart_mappable_builder: ^1.1.0
  jaspr_builder: ^0.1.0
  jaspr_test: ^0.1.0
  lints: ^1.0.0
  mdc_web: ^0.6.0
  test: ^1.16.0
  webdev: ^2.7.7
  yaml_writer: ^1.0.1