name: jaspr_test
description: Testing utilities for jaspr.
version: 0.1.0
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  domino: ^0.8.1
  html: ^0.15.0
  http: ^0.13.4
  jaspr: ^0.1.0
  meta: ^1.7.0
  test: ^1.19.5

dev_dependencies:
  lints: ^1.0.1