name: jaspr_riverpod
description: Riverpod for jaspr
version: 0.1.0-dev.1
homepage: https://github.com/schultek/jaspr
issue_tracker: https://github.com/schultek/jaspr/issues

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  jaspr: ^0.1.0
  meta: ^1.8.0
  riverpod: ^2.0.0-dev.4

dev_dependencies:
  jaspr_test: ^0.1.0
  lints: ^1.0.0
  test: ^1.16.0